import Head from 'next/head'
import Image from 'next/legacy/image'
import { useRouter } from 'next/router'
import { ImageContainer, ProductContainer, ProductDetails } from '../../styles/pages/product'

export default function Product() {
  const { query } = useRouter()
  return (
    <>
      <Head>
        <title>Ignite-Shop | Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductContainer>
        <ImageContainer>
          
        </ImageContainer>
        <ProductDetails>
          <h1>Camiseta x</h1>
          <span>R$ 79,90</span>

          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quo, exercitationem a voluptate, maiores tempora dolorum doloremque deserunt impedit consequatur amet excepturi hic obcaecati accusantium quia consequuntur. Quia vitae quam inventore.</p>

          <button>Comprar agora</button>
        </ProductDetails>
      </ProductContainer>
    </>
  )
}