import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Product() {
  const { query } = useRouter()
  return (
    <div>
      <Head>
        <title>Ignite-Shop | Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Product: {JSON.stringify(query)}</h1>
    </div>
  )
}