import Head from 'next/head'
import Image from 'next/legacy/image'
import { HomeConatiner, Product } from '../styles/pages/home'

import camiseta1 from '../assets/camisetas/camisa-1.png'
import camiseta2 from '../assets/camisetas/camisa-2.png'
import camiseta3 from '../assets/camisetas/camisa-3.png'
import camiseta4 from '../assets/camisetas/camisa-4.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite-Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeConatiner>
        <Product>
          <Image
            src={camiseta1}
            width={520}
            height={480}
          />

          <footer>
            <strong>Camiseta</strong>
            <span>R$ 79,90</span>
          </footer>
        </Product>
        <Product>
          <Image
            src={camiseta2}
            width={520}
            height={480}
          />

          <footer>
            <strong>Camiseta</strong>
            <span>R$ 79,90</span>
          </footer>
        </Product>
      </HomeConatiner>
    </>
  )
}
