import Head from 'next/head'
import Image from 'next/legacy/image'
import useEmblaCarousel from 'embla-carousel-react'
import { HomeConatiner, Product, SliderContainer } from '../styles/pages/home'

import { stripe } from '../lib/stripe'
import { GetStaticProps } from 'next'
import Stripe from 'stripe'

interface HomeProps {
  products: {
    id: string
    name: string
    price: string
    imageUrl: string
  }[]
}

export default function Home({ products }: HomeProps) {
  const [emblaRef] = useEmblaCarousel({
    align: 'start',
    skipSnaps: false,
    dragFree: true
  })

  return (
    <>
      <Head>
        <title>Ignite-Shop | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ overflow: "hidden", width: "100%"}}>
        <HomeConatiner>
          <div ref={emblaRef} className="embla">
            <SliderContainer className="embla__container container">
              {products.map(product => (
                  <Product href={`/product/${product.id}`} key={product.id} className="embla__slide"  prefetch={false}>
                      <Image
                        src={product.imageUrl}
                        width={520}
                        height={480}
                      />

                      <footer>
                        <strong>{product.name}</strong>
                        <span>{product.price}</span>
                      </footer>
                  </Product> 
              ))}
            </SliderContainer>
          </div>
        </HomeConatiner>
      </div>

    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await stripe.products.list({
    expand: ['data.default_price']
  })


  const products = response.data.map(product => {
    const price = product.default_price as Stripe.Price

    return {
      id: product.id,
      name: product.name,
      imageUrl: product.images[0],
      price: new Intl.NumberFormat('pt-BR', {
        style: 'currency',
        currency: 'BRL',
      }).format(price.unit_amount / 100)
    }
  })
  return {
    props: {
      products
    },
    revalidate: 60 * 60 * 2, // 2 horas
  }
}
